merge the dev branch with the master branch
kramlex/improve_edu_task pull request #5
Opened 2021-04-03 09:04 UTC by kramlex

2021-04-07 07:34 UTC, DmitryTetenyuk requested changes

2021-04-07 07:34 UTC, DmitryTetenyuk commented on improve_edu_task.xcodeproj/xcuserdata/markdubkov.xcuserdatad/xcschemes/xcschememanagement.plist
> +		<key>Sample-iOS (Playground) 1.xcscheme</key>
xcuserdata не должна быть в коммитах

2021-04-07 07:34 UTC, DmitryTetenyuk commented on improve_edu_task/Modules/ContactsDetailsViewController/Cells/ContactsDetailsCollectionViewCell.swift
> +extension ContactsDetailsCollectionViewCell: UITableViewDataSource,UITableViewDelegate {
Делегат таблицы внутри ячейки коллекшн вью?

2021-04-07 07:34 UTC, DmitryTetenyuk commented on improve_edu_task/Modules/ContactsModule/ContactsViewModel/ContactsViewModel.swift
> +
лишняя пустая строка

2021-04-07 07:34 UTC, DmitryTetenyuk commented on improve_edu_task/Modules/ContactsDetailsViewController/Cells/ContactsDetailsCollectionViewCell.swift
> +extension ContactsDetailsCollectionViewCell: UITableViewDataSource,UITableViewDelegate {
Делегат таблицы внутри ячейки коллекшн вью?

2021-04-07 07:34 UTC, DmitryTetenyuk commented on improve_edu_task/Modules/ContactsModule/ContactsViewModel/ContactsViewModel.swift
> +                guard let result = try? JSONDecoder().decode(CharactersResponse.self, from: data) else { return }
два guard let подряд, заменяется перечислением результатов через запятую

2021-04-08 07:22 UTC, DmitryTetenyuk requested changes

2021-04-08 07:22 UTC, DmitryTetenyuk commented on improve_edu_task/Model/Characters.swift
> +    case the07081993 = "07-08-1993"
не уверен что это енам, скорее date либо string

2021-04-08 14:23 UTC, kramlex commented on improve_edu_task/Model/Characters.swift
> +    case the07081993 = "07-08-1993"
Да сгенерилось не очень круто, исправил!

2021-04-08 14:23 UTC, kramlex commented on improve_edu_task/Model/Characters.swift
> +    case the07081993 = "07-08-1993"
Сделал стринг, все равно пока мы не используем это поле для чего-то, кроме вывода

2021-04-09 05:13 UTC, DmitryTetenyuk approved these changes

2021-04-09 05:15 UTC, merged